export const INVENTORY_PROVIDER =
    'INVENTORY_PROVIDER';
export const DISTANCE_PROVIDER = Symbol('DISTANCE_PROVIDER');
export const SOURCE_CONFIRMATION_PROVIDER =
    Symbol('SOURCE_CONFIRMATION_PROVIDER');